import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Sidebar from "@/components/Sidebar";
import SidebarProvider from "@/context/SidebarContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex">
        <SidebarProvider>
          <Sidebar />
        </SidebarProvider>
        <div className="w-4/5">{children}</div>
      </body>
    </html>
  );
}
